import type { CourseModule, Proposal } from '../types/proposal';

interface OpenPrintOpts {
  title: string;
  bodyHtml: string;
}

/**
 * Open a new tab with a print-friendly HTML doc and trigger the browser's
 * print dialog. Users pick "Save as PDF" as the destination. Works in every
 * modern browser without extra deps and outputs a clean PDF that can be
 * uploaded into Articulate Rise / Storyline as a resource.
 */
function openPrintWindow({ title, bodyHtml }: OpenPrintOpts) {
  const win = window.open('', '_blank');
  if (!win) {
    alert('Popup blocked — please allow popups for this site to export PDFs.');
    return;
  }
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(title)}</title>
  <style>
    :root { color-scheme: light; }
    * { box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
      color: #0f172a;
      line-height: 1.5;
      margin: 40px;
      max-width: 780px;
    }
    h1 { font-size: 26px; margin: 0 0 4px; color: #4c1d95; }
    h2 { font-size: 18px; margin: 24px 0 8px; color: #4c1d95; border-bottom: 1px solid #ddd6fe; padding-bottom: 4px; }
    h3 { font-size: 14px; margin: 16px 0 4px; color: #334155; text-transform: uppercase; letter-spacing: 0.04em; font-weight: 600; }
    p, li { font-size: 13px; }
    .muted { color: #64748b; font-size: 12px; margin-bottom: 20px; }
    .pill { display: inline-block; background: #ede9fe; color: #5b21b6; border-radius: 999px; padding: 2px 10px; font-size: 11px; font-weight: 600; margin-right: 6px; margin-bottom: 4px; }
    .field { margin: 10px 0 14px; }
    .field-label { font-size: 11px; text-transform: uppercase; letter-spacing: 0.06em; color: #6b21a8; font-weight: 700; margin-bottom: 3px; }
    .field-value { white-space: pre-wrap; }
    .empty { color: #94a3b8; font-style: italic; }
    table { border-collapse: collapse; width: 100%; margin: 8px 0 14px; }
    td, th { border: 1px solid #e2e8f0; padding: 6px 8px; font-size: 12px; text-align: left; vertical-align: top; }
    th { background: #f8fafc; }
    .kv { display: grid; grid-template-columns: 180px 1fr; gap: 4px 12px; margin: 10px 0; }
    .kv > .k { font-weight: 600; color: #475569; font-size: 12px; }
    .kv > .v { font-size: 13px; white-space: pre-wrap; }
    ul.obj { padding-left: 18px; margin: 4px 0; }
    ul.obj li { margin-bottom: 3px; }
    .bloom { display: inline-block; padding: 1px 8px; margin-right: 6px; border-radius: 999px; background: #ede9fe; color: #5b21b6; font-size: 10px; font-weight: 700; text-transform: uppercase; }
    footer { margin-top: 32px; font-size: 10px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 8px; }
    @media print {
      body { margin: 24px; }
      .no-print { display: none; }
    }
    .toolbar { position: sticky; top: 0; background: #f8fafc; border-bottom: 1px solid #e2e8f0; padding: 8px 0 12px; margin: -40px -40px 20px; padding-left: 40px; padding-right: 40px; }
    .toolbar button {
      background: #7c3aed; color: white; border: none; border-radius: 6px;
      padding: 8px 14px; font-size: 13px; font-weight: 600; cursor: pointer; margin-right: 8px;
    }
    .toolbar .hint { font-size: 11px; color: #64748b; }
  </style>
</head>
<body>
  <div class="toolbar no-print">
    <button onclick="window.print()">Save as PDF</button>
    <span class="hint">Pick <strong>Save as PDF</strong> as the print destination — the PDF is ready to upload into Articulate.</span>
  </div>
  ${bodyHtml}
  <footer>Generated by the Thrive Academy course builder · ${new Date().toLocaleDateString()}</footer>
  <script>
    // Auto-open the print dialog once the doc is painted.
    window.addEventListener('load', () => setTimeout(() => window.print(), 250));
  </script>
</body>
</html>`;
  win.document.open();
  win.document.write(html);
  win.document.close();
}

function escapeHtml(s: string): string {
  return (s || '').replace(/[&<>"']/g, (c) =>
    c === '&' ? '&amp;' : c === '<' ? '&lt;' : c === '>' ? '&gt;' : c === '"' ? '&quot;' : '&#39;'
  );
}

function field(label: string, value: string | undefined | null): string {
  const v = (value || '').trim();
  const inner = v ? escapeHtml(v) : '<span class="empty">Not yet filled in.</span>';
  return `<div class="field"><div class="field-label">${escapeHtml(label)}</div><div class="field-value">${inner}</div></div>`;
}

function objectivesList(objs: { text: string; bloom: string }[]): string {
  const items = objs.filter((o) => o.text.trim());
  if (items.length === 0) return '<div class="empty">No learning objectives yet.</div>';
  const rows = items
    .map(
      (o) =>
        `<li>${o.bloom ? `<span class="bloom">${escapeHtml(o.bloom)}</span>` : ''}${escapeHtml(o.text)}</li>`
    )
    .join('');
  return `<ul class="obj">${rows}</ul>`;
}

function courseHeader(proposal: Proposal): string {
  const co = proposal.course_overview;
  return `
    <h1>${escapeHtml(co.course_name || 'Untitled course')}</h1>
    <div class="muted">${escapeHtml([co.course_type, co.course_format, co.duration].filter(Boolean).join(' · '))}${
      co.faculty ? ' — ' + escapeHtml(co.faculty) : ''
    }</div>`;
}

export function exportSection1Pdf(proposal: Proposal) {
  const co = proposal.course_overview;
  const d = proposal.design;
  const body = `
    ${courseHeader(proposal)}
    <h2>Section 1 · Course-level design</h2>
    <div class="kv">
      <div class="k">Course name</div><div class="v">${escapeHtml(co.course_name || '—')}</div>
      <div class="k">Intended audience</div><div class="v">${escapeHtml(co.intended_audiences || '—')}</div>
      <div class="k">Course type</div><div class="v">${escapeHtml(co.course_type || '—')}</div>
      <div class="k">Course format</div><div class="v">${escapeHtml(co.course_format || '—')}</div>
      <div class="k">Faculty</div><div class="v">${escapeHtml(co.faculty || '—')}</div>
    </div>
    ${field('Course essential question', d.essential_question)}
    ${field('Course-level learning objectives', d.learning_objectives)}
    ${field('Course structure / arc', d.course_structure)}
  `;
  openPrintWindow({
    title: `${co.course_name || 'Course'} — Section 1 (Course-level design)`,
    bodyHtml: body,
  });
}

export function exportSection3Pdf(proposal: Proposal) {
  const co = proposal.course_overview;
  const d = proposal.design;
  const body = `
    ${courseHeader(proposal)}
    <h2>Section 3 · Assessment, support &amp; continuous improvement</h2>
    ${field('Technology needs', d.technology_needs)}
    ${field('Grading scheme & assessment methods', d.assessment_methods)}
    ${field('Student support', d.student_support)}
    ${field('Evaluation & outcomes', d.evaluation_outcomes)}
    ${field('CQI & staying current', d.cqi)}
  `;
  openPrintWindow({
    title: `${co.course_name || 'Course'} — Section 3 (Assessment & support)`,
    bodyHtml: body,
  });
}

export function exportModulePdf(
  proposal: Proposal,
  module: CourseModule,
  index: number
) {
  const co = proposal.course_overview;
  const courseEQ = proposal.design.essential_question;
  const features =
    module.interactive_features.length > 0
      ? module.interactive_features.map((f) => `<span class="pill">${escapeHtml(f)}</span>`).join('')
      : '<span class="empty">None selected.</span>';
  const materials =
    module.materials.length > 0
      ? '<ul>' +
        module.materials.map((m) => `<li>${escapeHtml(m.filename)}</li>`).join('') +
        '</ul>'
      : '<div class="empty">No materials uploaded.</div>';

  const body = `
    ${courseHeader(proposal)}
    <h2>Module ${index + 1} · ${escapeHtml(module.module_name || 'Untitled module')}</h2>
    <div class="kv">
      <div class="k">Contact hours</div><div class="v">${escapeHtml(module.contact_hours || '—')}</div>
      <div class="k">Format</div><div class="v">${escapeHtml(module.format || '—')}</div>
      <div class="k">Faculty</div><div class="v">${escapeHtml(module.faculty || '—')}</div>
    </div>
    ${courseEQ ? `<div class="field"><div class="field-label">Course essential question</div><div class="field-value">${escapeHtml(courseEQ)}</div></div>` : ''}
    ${field('Module essential question', module.essential_question)}
    <div class="field"><div class="field-label">Learning objectives (Bloom-tagged)</div>${objectivesList(module.objectives)}</div>
    ${field('Critical information', module.critical_information)}
    ${field('Opportunities for engagement', module.engagement_opportunities)}
    <div class="field"><div class="field-label">Interactive features</div><div>${features}</div></div>
    ${field('Interactive features — notes', module.interactive_features_notes)}
    ${field('Required readings', module.required_readings)}
    ${field('Recommended readings', module.recommended_readings)}
    ${field('Assignments', module.assignments)}
    <div class="field"><div class="field-label">Uploaded materials</div>${materials}</div>
  `;
  openPrintWindow({
    title: `${co.course_name || 'Course'} — Module ${index + 1}: ${module.module_name || 'Untitled'}`,
    bodyHtml: body,
  });
}
